#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiberMvc.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="liber")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEstadoCivil(EstadoCivil instance);
    partial void UpdateEstadoCivil(EstadoCivil instance);
    partial void DeleteEstadoCivil(EstadoCivil instance);
    partial void InsertTipoUsuario(TipoUsuario instance);
    partial void UpdateTipoUsuario(TipoUsuario instance);
    partial void DeleteTipoUsuario(TipoUsuario instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertGrauInstrucao(GrauInstrucao instance);
    partial void UpdateGrauInstrucao(GrauInstrucao instance);
    partial void DeleteGrauInstrucao(GrauInstrucao instance);
    partial void InsertArtigo(Artigo instance);
    partial void UpdateArtigo(Artigo instance);
    partial void DeleteArtigo(Artigo instance);
    #endregion
		
		public DBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["liberConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<EstadoCivil> EstadoCivils
		{
			get
			{
				return this.GetTable<EstadoCivil>();
			}
		}
		
		public System.Data.Linq.Table<TipoUsuario> TipoUsuarios
		{
			get
			{
				return this.GetTable<TipoUsuario>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<GrauInstrucao> GrauInstrucaos
		{
			get
			{
				return this.GetTable<GrauInstrucao>();
			}
		}
		
		public System.Data.Linq.Table<Artigo> Artigos
		{
			get
			{
				return this.GetTable<Artigo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.EstadoCivil")]
	public partial class EstadoCivil : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EstadoCivilID;
		
		private string _Descricao;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEstadoCivilIDChanging(int value);
    partial void OnEstadoCivilIDChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public EstadoCivil()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCivilID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int EstadoCivilID
		{
			get
			{
				return this._EstadoCivilID;
			}
			set
			{
				if ((this._EstadoCivilID != value))
				{
					this.OnEstadoCivilIDChanging(value);
					this.SendPropertyChanging();
					this._EstadoCivilID = value;
					this.SendPropertyChanged("EstadoCivilID");
					this.OnEstadoCivilIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="NVarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoCivil_Usuario", Storage="_Usuarios", ThisKey="EstadoCivilID", OtherKey="EstadoCivilID")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.EstadoCivil = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.EstadoCivil = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.TipoUsuario")]
	public partial class TipoUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TipoUsuarioID;
		
		private string _Descricao;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipoUsuarioIDChanging(int value);
    partial void OnTipoUsuarioIDChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public TipoUsuario()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuarioID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TipoUsuarioID
		{
			get
			{
				return this._TipoUsuarioID;
			}
			set
			{
				if ((this._TipoUsuarioID != value))
				{
					this.OnTipoUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._TipoUsuarioID = value;
					this.SendPropertyChanged("TipoUsuarioID");
					this.OnTipoUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="NVarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuario", Storage="_Usuarios", ThisKey="TipoUsuarioID", OtherKey="TipoUsuarioID")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.TipoUsuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioID;
		
		private int _TipoUsuarioID;
		
		private string _Nome;
		
		private string _Email;
		
		private string _CPF;
		
		private bool _ReceberNewsletter;
		
		private string _Senha;
		
		private System.Nullable<System.DateTime> _DataNasc;
		
		private string _Sexo;
		
		private bool _Banido;
		
		private string _Naturalidade;
		
		private string _NomePai;
		
		private string _NomeMae;
		
		private System.Nullable<int> _EstadoCivilID;
		
		private string _Profissao;
		
		private System.Nullable<int> _GrauInstrucaoID;
		
		private string _Endereco;
		
		private string _Cidade;
		
		private string _Estado;
		
		private string _CEP;
		
		private string _Telefone;
		
		private string _TituloEleitor;
		
		private string _Zona;
		
		private string _Secao;
		
		private string _MunicipioUF;
		
		private bool _OutroPartido;
		
		private string _OutroPartidoQual;
		
		private EntitySet<Artigo> _Artigos;
		
		private EntityRef<EstadoCivil> _EstadoCivil;
		
		private EntityRef<TipoUsuario> _TipoUsuario;
		
		private EntityRef<GrauInstrucao> _GrauInstrucao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnTipoUsuarioIDChanging(int value);
    partial void OnTipoUsuarioIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnReceberNewsletterChanging(bool value);
    partial void OnReceberNewsletterChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnDataNascChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNascChanged();
    partial void OnSexoChanging(string value);
    partial void OnSexoChanged();
    partial void OnBanidoChanging(bool value);
    partial void OnBanidoChanged();
    partial void OnNaturalidadeChanging(string value);
    partial void OnNaturalidadeChanged();
    partial void OnNomePaiChanging(string value);
    partial void OnNomePaiChanged();
    partial void OnNomeMaeChanging(string value);
    partial void OnNomeMaeChanged();
    partial void OnEstadoCivilIDChanging(System.Nullable<int> value);
    partial void OnEstadoCivilIDChanged();
    partial void OnProfissaoChanging(string value);
    partial void OnProfissaoChanged();
    partial void OnGrauInstrucaoIDChanging(System.Nullable<int> value);
    partial void OnGrauInstrucaoIDChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnTituloEleitorChanging(string value);
    partial void OnTituloEleitorChanged();
    partial void OnZonaChanging(string value);
    partial void OnZonaChanged();
    partial void OnSecaoChanging(string value);
    partial void OnSecaoChanged();
    partial void OnMunicipioUFChanging(string value);
    partial void OnMunicipioUFChanged();
    partial void OnOutroPartidoChanging(bool value);
    partial void OnOutroPartidoChanged();
    partial void OnOutroPartidoQualChanging(string value);
    partial void OnOutroPartidoQualChanged();
    #endregion
		
		public Usuario()
		{
			this._Artigos = new EntitySet<Artigo>(new Action<Artigo>(this.attach_Artigos), new Action<Artigo>(this.detach_Artigos));
			this._EstadoCivil = default(EntityRef<EstadoCivil>);
			this._TipoUsuario = default(EntityRef<TipoUsuario>);
			this._GrauInstrucao = default(EntityRef<GrauInstrucao>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuarioID", DbType="Int NOT NULL")]
		public int TipoUsuarioID
		{
			get
			{
				return this._TipoUsuarioID;
			}
			set
			{
				if ((this._TipoUsuarioID != value))
				{
					if (this._TipoUsuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._TipoUsuarioID = value;
					this.SendPropertyChanged("TipoUsuarioID");
					this.OnTipoUsuarioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(250)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(250)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="NVarChar(18)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceberNewsletter", DbType="Bit NOT NULL")]
		public bool ReceberNewsletter
		{
			get
			{
				return this._ReceberNewsletter;
			}
			set
			{
				if ((this._ReceberNewsletter != value))
				{
					this.OnReceberNewsletterChanging(value);
					this.SendPropertyChanging();
					this._ReceberNewsletter = value;
					this.SendPropertyChanged("ReceberNewsletter");
					this.OnReceberNewsletterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="NVarChar(50)")]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNasc", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataNasc
		{
			get
			{
				return this._DataNasc;
			}
			set
			{
				if ((this._DataNasc != value))
				{
					this.OnDataNascChanging(value);
					this.SendPropertyChanging();
					this._DataNasc = value;
					this.SendPropertyChanged("DataNasc");
					this.OnDataNascChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="NVarChar(1)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Banido", DbType="Bit NOT NULL")]
		public bool Banido
		{
			get
			{
				return this._Banido;
			}
			set
			{
				if ((this._Banido != value))
				{
					this.OnBanidoChanging(value);
					this.SendPropertyChanging();
					this._Banido = value;
					this.SendPropertyChanged("Banido");
					this.OnBanidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naturalidade", DbType="NVarChar(50)")]
		public string Naturalidade
		{
			get
			{
				return this._Naturalidade;
			}
			set
			{
				if ((this._Naturalidade != value))
				{
					this.OnNaturalidadeChanging(value);
					this.SendPropertyChanging();
					this._Naturalidade = value;
					this.SendPropertyChanged("Naturalidade");
					this.OnNaturalidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomePai", DbType="NVarChar(250)")]
		public string NomePai
		{
			get
			{
				return this._NomePai;
			}
			set
			{
				if ((this._NomePai != value))
				{
					this.OnNomePaiChanging(value);
					this.SendPropertyChanging();
					this._NomePai = value;
					this.SendPropertyChanged("NomePai");
					this.OnNomePaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeMae", DbType="NVarChar(250)")]
		public string NomeMae
		{
			get
			{
				return this._NomeMae;
			}
			set
			{
				if ((this._NomeMae != value))
				{
					this.OnNomeMaeChanging(value);
					this.SendPropertyChanging();
					this._NomeMae = value;
					this.SendPropertyChanged("NomeMae");
					this.OnNomeMaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCivilID", DbType="Int")]
		public System.Nullable<int> EstadoCivilID
		{
			get
			{
				return this._EstadoCivilID;
			}
			set
			{
				if ((this._EstadoCivilID != value))
				{
					if (this._EstadoCivil.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEstadoCivilIDChanging(value);
					this.SendPropertyChanging();
					this._EstadoCivilID = value;
					this.SendPropertyChanged("EstadoCivilID");
					this.OnEstadoCivilIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profissao", DbType="NVarChar(50)")]
		public string Profissao
		{
			get
			{
				return this._Profissao;
			}
			set
			{
				if ((this._Profissao != value))
				{
					this.OnProfissaoChanging(value);
					this.SendPropertyChanging();
					this._Profissao = value;
					this.SendPropertyChanged("Profissao");
					this.OnProfissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrauInstrucaoID", DbType="Int")]
		public System.Nullable<int> GrauInstrucaoID
		{
			get
			{
				return this._GrauInstrucaoID;
			}
			set
			{
				if ((this._GrauInstrucaoID != value))
				{
					if (this._GrauInstrucao.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGrauInstrucaoIDChanging(value);
					this.SendPropertyChanging();
					this._GrauInstrucaoID = value;
					this.SendPropertyChanged("GrauInstrucaoID");
					this.OnGrauInstrucaoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Endereco", DbType="NVarChar(250)")]
		public string Endereco
		{
			get
			{
				return this._Endereco;
			}
			set
			{
				if ((this._Endereco != value))
				{
					this.OnEnderecoChanging(value);
					this.SendPropertyChanging();
					this._Endereco = value;
					this.SendPropertyChanged("Endereco");
					this.OnEnderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="NVarChar(250)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NVarChar(2)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="NVarChar(9)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="NVarChar(50)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TituloEleitor", DbType="NVarChar(12)")]
		public string TituloEleitor
		{
			get
			{
				return this._TituloEleitor;
			}
			set
			{
				if ((this._TituloEleitor != value))
				{
					this.OnTituloEleitorChanging(value);
					this.SendPropertyChanging();
					this._TituloEleitor = value;
					this.SendPropertyChanged("TituloEleitor");
					this.OnTituloEleitorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zona", DbType="NVarChar(4)")]
		public string Zona
		{
			get
			{
				return this._Zona;
			}
			set
			{
				if ((this._Zona != value))
				{
					this.OnZonaChanging(value);
					this.SendPropertyChanging();
					this._Zona = value;
					this.SendPropertyChanged("Zona");
					this.OnZonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secao", DbType="NVarChar(4)")]
		public string Secao
		{
			get
			{
				return this._Secao;
			}
			set
			{
				if ((this._Secao != value))
				{
					this.OnSecaoChanging(value);
					this.SendPropertyChanging();
					this._Secao = value;
					this.SendPropertyChanged("Secao");
					this.OnSecaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MunicipioUF", DbType="NVarChar(250)")]
		public string MunicipioUF
		{
			get
			{
				return this._MunicipioUF;
			}
			set
			{
				if ((this._MunicipioUF != value))
				{
					this.OnMunicipioUFChanging(value);
					this.SendPropertyChanging();
					this._MunicipioUF = value;
					this.SendPropertyChanged("MunicipioUF");
					this.OnMunicipioUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutroPartido", DbType="Bit NOT NULL")]
		public bool OutroPartido
		{
			get
			{
				return this._OutroPartido;
			}
			set
			{
				if ((this._OutroPartido != value))
				{
					this.OnOutroPartidoChanging(value);
					this.SendPropertyChanging();
					this._OutroPartido = value;
					this.SendPropertyChanged("OutroPartido");
					this.OnOutroPartidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutroPartidoQual", DbType="NVarChar(50)")]
		public string OutroPartidoQual
		{
			get
			{
				return this._OutroPartidoQual;
			}
			set
			{
				if ((this._OutroPartidoQual != value))
				{
					this.OnOutroPartidoQualChanging(value);
					this.SendPropertyChanging();
					this._OutroPartidoQual = value;
					this.SendPropertyChanged("OutroPartidoQual");
					this.OnOutroPartidoQualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Artigo", Storage="_Artigos", ThisKey="UsuarioID", OtherKey="EditorID")]
		public EntitySet<Artigo> Artigos
		{
			get
			{
				return this._Artigos;
			}
			set
			{
				this._Artigos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="EstadoCivil_Usuario", Storage="_EstadoCivil", ThisKey="EstadoCivilID", OtherKey="EstadoCivilID", IsForeignKey=true)]
		public EstadoCivil EstadoCivil
		{
			get
			{
				return this._EstadoCivil.Entity;
			}
			set
			{
				EstadoCivil previousValue = this._EstadoCivil.Entity;
				if (((previousValue != value) 
							|| (this._EstadoCivil.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EstadoCivil.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._EstadoCivil.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._EstadoCivilID = value.EstadoCivilID;
					}
					else
					{
						this._EstadoCivilID = default(Nullable<int>);
					}
					this.SendPropertyChanged("EstadoCivil");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoUsuario_Usuario", Storage="_TipoUsuario", ThisKey="TipoUsuarioID", OtherKey="TipoUsuarioID", IsForeignKey=true)]
		public TipoUsuario TipoUsuario
		{
			get
			{
				return this._TipoUsuario.Entity;
			}
			set
			{
				TipoUsuario previousValue = this._TipoUsuario.Entity;
				if (((previousValue != value) 
							|| (this._TipoUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoUsuario.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._TipoUsuario.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._TipoUsuarioID = value.TipoUsuarioID;
					}
					else
					{
						this._TipoUsuarioID = default(int);
					}
					this.SendPropertyChanged("TipoUsuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GrauInstrucao_Usuario", Storage="_GrauInstrucao", ThisKey="GrauInstrucaoID", OtherKey="GrauInstrucaoID", IsForeignKey=true)]
		public GrauInstrucao GrauInstrucao
		{
			get
			{
				return this._GrauInstrucao.Entity;
			}
			set
			{
				GrauInstrucao previousValue = this._GrauInstrucao.Entity;
				if (((previousValue != value) 
							|| (this._GrauInstrucao.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GrauInstrucao.Entity = null;
						previousValue.Usuarios.Remove(this);
					}
					this._GrauInstrucao.Entity = value;
					if ((value != null))
					{
						value.Usuarios.Add(this);
						this._GrauInstrucaoID = value.GrauInstrucaoID;
					}
					else
					{
						this._GrauInstrucaoID = default(Nullable<int>);
					}
					this.SendPropertyChanged("GrauInstrucao");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Artigos(Artigo entity)
		{
			this.SendPropertyChanging();
			entity.Editor = this;
		}
		
		private void detach_Artigos(Artigo entity)
		{
			this.SendPropertyChanging();
			entity.Editor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.GrauInstrucao")]
	public partial class GrauInstrucao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GrauInstrucaoID;
		
		private string _Descricao;
		
		private EntitySet<Usuario> _Usuarios;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGrauInstrucaoIDChanging(int value);
    partial void OnGrauInstrucaoIDChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public GrauInstrucao()
		{
			this._Usuarios = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuarios), new Action<Usuario>(this.detach_Usuarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrauInstrucaoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int GrauInstrucaoID
		{
			get
			{
				return this._GrauInstrucaoID;
			}
			set
			{
				if ((this._GrauInstrucaoID != value))
				{
					this.OnGrauInstrucaoIDChanging(value);
					this.SendPropertyChanging();
					this._GrauInstrucaoID = value;
					this.SendPropertyChanged("GrauInstrucaoID");
					this.OnGrauInstrucaoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="NVarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GrauInstrucao_Usuario", Storage="_Usuarios", ThisKey="GrauInstrucaoID", OtherKey="GrauInstrucaoID")]
		public EntitySet<Usuario> Usuarios
		{
			get
			{
				return this._Usuarios;
			}
			set
			{
				this._Usuarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.GrauInstrucao = this;
		}
		
		private void detach_Usuarios(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.GrauInstrucao = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="liber.Artigo")]
	public partial class Artigo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ArtigoID;
		
		private int _EditorID;
		
		private string _Titulo;
		
		private string _Chamada;
		
		private string _Conteudo;
		
		private bool _Publicado;
		
		private System.DateTime _PublicadoEm;
		
		private System.DateTime _CriadoEm;
		
		private string _Autor;
		
		private string _Fonte;
		
		private EntityRef<Usuario> _Editor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnArtigoIDChanging(int value);
    partial void OnArtigoIDChanged();
    partial void OnEditorIDChanging(int value);
    partial void OnEditorIDChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnChamadaChanging(string value);
    partial void OnChamadaChanged();
    partial void OnConteudoChanging(string value);
    partial void OnConteudoChanged();
    partial void OnPublicadoChanging(bool value);
    partial void OnPublicadoChanged();
    partial void OnPublicadoEmChanging(System.DateTime value);
    partial void OnPublicadoEmChanged();
    partial void OnCriadoEmChanging(System.DateTime value);
    partial void OnCriadoEmChanged();
    partial void OnAutorChanging(string value);
    partial void OnAutorChanged();
    partial void OnFonteChanging(string value);
    partial void OnFonteChanged();
    #endregion
		
		public Artigo()
		{
			this._Editor = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArtigoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ArtigoID
		{
			get
			{
				return this._ArtigoID;
			}
			set
			{
				if ((this._ArtigoID != value))
				{
					this.OnArtigoIDChanging(value);
					this.SendPropertyChanging();
					this._ArtigoID = value;
					this.SendPropertyChanged("ArtigoID");
					this.OnArtigoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorID", DbType="Int NOT NULL")]
		public int EditorID
		{
			get
			{
				return this._EditorID;
			}
			set
			{
				if ((this._EditorID != value))
				{
					if (this._Editor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEditorIDChanging(value);
					this.SendPropertyChanging();
					this._EditorID = value;
					this.SendPropertyChanged("EditorID");
					this.OnEditorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(250)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chamada", DbType="NVarChar(1000)")]
		public string Chamada
		{
			get
			{
				return this._Chamada;
			}
			set
			{
				if ((this._Chamada != value))
				{
					this.OnChamadaChanging(value);
					this.SendPropertyChanging();
					this._Chamada = value;
					this.SendPropertyChanged("Chamada");
					this.OnChamadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conteudo", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Conteudo
		{
			get
			{
				return this._Conteudo;
			}
			set
			{
				if ((this._Conteudo != value))
				{
					this.OnConteudoChanging(value);
					this.SendPropertyChanging();
					this._Conteudo = value;
					this.SendPropertyChanged("Conteudo");
					this.OnConteudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publicado", DbType="Bit NOT NULL")]
		public bool Publicado
		{
			get
			{
				return this._Publicado;
			}
			set
			{
				if ((this._Publicado != value))
				{
					this.OnPublicadoChanging(value);
					this.SendPropertyChanging();
					this._Publicado = value;
					this.SendPropertyChanged("Publicado");
					this.OnPublicadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublicadoEm", DbType="DateTime NOT NULL")]
		public System.DateTime PublicadoEm
		{
			get
			{
				return this._PublicadoEm;
			}
			set
			{
				if ((this._PublicadoEm != value))
				{
					this.OnPublicadoEmChanging(value);
					this.SendPropertyChanging();
					this._PublicadoEm = value;
					this.SendPropertyChanged("PublicadoEm");
					this.OnPublicadoEmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CriadoEm", DbType="DateTime NOT NULL")]
		public System.DateTime CriadoEm
		{
			get
			{
				return this._CriadoEm;
			}
			set
			{
				if ((this._CriadoEm != value))
				{
					this.OnCriadoEmChanging(value);
					this.SendPropertyChanging();
					this._CriadoEm = value;
					this.SendPropertyChanged("CriadoEm");
					this.OnCriadoEmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Autor", DbType="NVarChar(250)")]
		public string Autor
		{
			get
			{
				return this._Autor;
			}
			set
			{
				if ((this._Autor != value))
				{
					this.OnAutorChanging(value);
					this.SendPropertyChanging();
					this._Autor = value;
					this.SendPropertyChanged("Autor");
					this.OnAutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fonte", DbType="NVarChar(500)")]
		public string Fonte
		{
			get
			{
				return this._Fonte;
			}
			set
			{
				if ((this._Fonte != value))
				{
					this.OnFonteChanging(value);
					this.SendPropertyChanging();
					this._Fonte = value;
					this.SendPropertyChanged("Fonte");
					this.OnFonteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Artigo", Storage="_Editor", ThisKey="EditorID", OtherKey="UsuarioID", IsForeignKey=true)]
		public Usuario Editor
		{
			get
			{
				return this._Editor.Entity;
			}
			set
			{
				Usuario previousValue = this._Editor.Entity;
				if (((previousValue != value) 
							|| (this._Editor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Editor.Entity = null;
						previousValue.Artigos.Remove(this);
					}
					this._Editor.Entity = value;
					if ((value != null))
					{
						value.Artigos.Add(this);
						this._EditorID = value.UsuarioID;
					}
					else
					{
						this._EditorID = default(int);
					}
					this.SendPropertyChanged("Editor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
